# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "VERSEN: VEReniging Software Engineering Nederland"
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  VERSEN is the Dutch National Association for Software Engineering.
  Its mission is to bring together researchers, educators and practitioners 
  in the field of software engineering in The Netherlands, who share the 
  common goals of advancing the field or software engineering, raising 
  public awareness of the challenges and opportunities of the field, 
  acquiring funding for groundbreaking research, and transferring 
  academic results to broader society.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

destination: _site

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]


collections:
  news:
    permalink: /news_items/:slug/
    output: true

plugins: [jekyll-paginate-v2]

sass:
  style: compressed

pagination:
  
  # Site-wide kill switch, disabled here it doesn't run at all 
  enabled: true
  # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
  debug: false
